name: handongsam
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0

  webview_flutter: ^0.3.15+1
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.14
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.15.0+1

  flutter_sparkline: ^0.1.0
  pie_chart: ^3.1.0
  bezier_chart: ^1.0.6
  flutter_swiper: ^1.1.6
  fl_chart: ^0.4.2
  charts_flutter: ^0.8.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - intensive.png
    - balance.png
    - food1.png
    - food2.png
    - food3.png
    - food4.png
    - food5.png
    - food6.png
    - select-food1.png
    - select-food2.png
    - select-food3.png
    - select-food4.png
    - select-food5.png
    - select_food6.png
    - poop1.png
    - poop2.jpg
    - poop3.jpg
    - poop4.jpg
    - poop5.jpg
    - poop6.jpg
    - water1.png
    - water2.png
    - shappiness.png
    - happiness1.png
    - frown-face1.png
    - sfrown-face.png

